spring:
  devtools:
    restart.enabled: true
    remote.restart.enabled: true


  # DBMS Setting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bootDB
    username: root
    password: '!Korea8080'


jpa:
  hibernate.ddl-auto: update
  properties:
    hibernate.show_sql: true
    hibernate.format_sql: true

thymeleaf:

  prefix: classpath:/html/
  suffix: .html
  mode: HTML5
  template-resolver-order: 0


# 외부에서 접근하는 경루
mvc:
  static-path-pattern: /static/**

# 서버의 폴더 개방하기
web:
  resources:
    static-locations: classpath:static/

# logback setup
logging:
  config: classpath:logback-local.xml
  level:
    com.callor.todo: debug
    org.springframework: INFO
    org.springframework.boot.autoconfigure: INFO
